// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Inquiry struct {
	ID        uuid.UUID
	ListingID uuid.NullUUID
	SenderID  uuid.NullUUID
	Status    sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Listing struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	Intent      string
	Title       string
	Description sql.NullString
	PriceRange  sql.NullString
	Location    string
	Category    string
	Status      sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type ListingImage struct {
	ID        uuid.UUID
	ListingID uuid.UUID
	Url       string
}

type Message struct {
	ID        uuid.UUID
	InquiryID uuid.NullUUID
	SenderID  uuid.NullUUID
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}
