// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Inquiry struct {
	ID        uuid.UUID
	ListingID uuid.UUID
	SenderID  uuid.UUID
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Listing struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Intent      string
	Title       string
	Description string
	Price       string
	Location    string
	Category    string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ListingImage struct {
	ID        uuid.UUID
	ListingID uuid.UUID
	Url       string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Message struct {
	ID        uuid.UUID
	InquiryID uuid.UUID
	SenderID  uuid.UUID
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
